<?php

namespace Tests;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
    }

    protected function tearDown(): void
    {
        $this->artisan('migrate:reset');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function checkResourceKeyIsValid(?string $resource_key): void
    {
        $pattern = '/^[a-f\d]{8}(-[a-f\d]{4}){4}[a-f\d]{8}$/i';
        $this->assertTrue((bool)preg_match($pattern, $resource_key));
    }

    protected function loggedInUser()
    {
        $user = User::factory()->create();
        $response = $this->actingAs($user);

        return $user->first();
    }
}
